#!/bin/env sh

printf "$$" > ~/.cache/pidofbar
sec=0

# MODULES
update_cpu () {
    cpu="C: $(grep -o "^[^ ]*" /proc/loadavg )"
}

update_memory () {
    memory="M: $(free -h | sed -n "2s/\([^ ]* *\)\{2\}\([^ ]*\).*/\2/p")"
}

update_time () {
    time="$(date "+%a %d %b %I:%M %P")"
}

update_vol () {
    vol="V: $(amixer sget Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
}

display () {
    printf "%s\n" " $event [$weather] [$memory $cpu] [$bat] [$backlight] [$vol] $time "
    xsetroot -name " $memory $cpu $vol $time "
}

trap	"update_vol;display"		"RTMIN"

while true
do
    sleep 1 & wait && {
        [ $((sec % 5 )) -eq 0 ] && update_time
        [ $((sec % 5 )) -eq 0 ] && update_vol
        [ $((sec % 5 )) -eq 0 ] && update_cpu
        [ $((sec % 5 )) -eq 0 ] && update_memory
        sec=$((sec + 1))
        display
    }
done

